-- Vylan — initial schema.
--
-- Conventions:
--   * Every domain table has a firm_id for tenant scoping (except `jobs`,
--     which is a global queue).
--   * UUID primary keys, generated by `gen_random_uuid()`.
--   * Enums are declared up front; widen them in a later migration if needed.

create extension if not exists "pgcrypto" with schema public;
create extension if not exists "citext" with schema public;

------------------------------------------------------------------------------
-- ENUMS
------------------------------------------------------------------------------

create type firm_plan as enum ('trial', 'solo', 'cabinet', 'cabinet_plus');
create type user_role as enum ('owner', 'staff');
create type user_locale as enum ('fr', 'en');
create type client_type as enum ('individual', 'business');
create type engagement_type as enum ('t1', 't2', 'bookkeeping', 'custom');
create type engagement_status as enum (
  'draft', 'sent', 'in_progress', 'complete', 'cancelled'
);
create type doc_type as enum (
  't4', 'rl1', 't5', 'rl3', 't3', 'rl16', 'noa',
  'bank_statement', 'credit_card_statement', 'receipt',
  't2202', 'rrsp', 'medical', 'donation', 'rental',
  'gst_hst_qst', 'trial_balance', 'gl_export', 'financials',
  'shareholder_loan', 'payroll_summary', 'capital_asset',
  'inventory', 'invoice', 'other'
);
create type request_item_status as enum (
  'pending', 'submitted', 'approved', 'rejected', 'na'
);
create type reminder_channel as enum ('email', 'sms');
create type reminder_status as enum ('scheduled', 'sent', 'failed', 'cancelled');
create type activity_actor as enum ('user', 'client', 'system');
create type job_status as enum ('pending', 'running', 'done', 'failed');

------------------------------------------------------------------------------
-- TABLES
------------------------------------------------------------------------------

create table firms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  locale_default user_locale not null default 'fr',
  logo_url text,
  brand_color text not null default '#1e293b',
  timezone text not null default 'America/Toronto',
  stripe_customer_id text,
  plan firm_plan not null default 'trial',
  created_at timestamptz not null default now()
);

create table users (
  -- Mirrors auth.users.id (1:1).
  id uuid primary key references auth.users(id) on delete cascade,
  firm_id uuid not null references firms(id) on delete cascade,
  email citext not null unique,
  name text not null,
  role user_role not null default 'staff',
  locale user_locale not null default 'fr',
  created_at timestamptz not null default now()
);
create index users_firm_id_idx on users(firm_id);

create table clients (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid not null references firms(id) on delete cascade,
  type client_type not null default 'individual',
  display_name text not null,
  email citext,
  phone text,
  locale user_locale not null default 'fr',
  external_ref text,
  notes text,
  created_at timestamptz not null default now(),
  archived_at timestamptz
);
create index clients_firm_id_idx on clients(firm_id);
create index clients_firm_archived_idx on clients(firm_id, archived_at);

create table engagements (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid not null references firms(id) on delete cascade,
  client_id uuid not null references clients(id) on delete cascade,
  title text not null,
  type engagement_type not null default 'custom',
  status engagement_status not null default 'draft',
  due_date date,
  sent_at timestamptz,
  completed_at timestamptz,
  magic_token text unique,
  magic_expires_at timestamptz,
  assigned_user_id uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index engagements_firm_id_idx on engagements(firm_id);
create index engagements_client_id_idx on engagements(client_id);
create index engagements_status_idx on engagements(status);
create index engagements_magic_token_idx on engagements(magic_token);

create table request_items (
  id uuid primary key default gen_random_uuid(),
  engagement_id uuid not null references engagements(id) on delete cascade,
  label text not null,
  label_fr text,
  description text,
  description_fr text,
  doc_type doc_type not null default 'other',
  required boolean not null default true,
  order_index integer not null default 0,
  status request_item_status not null default 'pending',
  approved_by uuid references users(id) on delete set null,
  approved_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now()
);
create index request_items_engagement_id_idx
  on request_items(engagement_id, order_index);
create index request_items_status_idx on request_items(status);

create table uploaded_files (
  id uuid primary key default gen_random_uuid(),
  request_item_id uuid not null references request_items(id) on delete cascade,
  engagement_id uuid not null references engagements(id) on delete cascade,
  storage_path text not null,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null,
  ai_classification text,
  ai_confidence numeric(4, 3),
  ai_extracted_fields jsonb,
  uploaded_at timestamptz not null default now(),
  uploaded_by_ip inet
);
create index uploaded_files_request_item_idx on uploaded_files(request_item_id);
create index uploaded_files_engagement_idx on uploaded_files(engagement_id);

create table reminders (
  id uuid primary key default gen_random_uuid(),
  engagement_id uuid not null references engagements(id) on delete cascade,
  channel reminder_channel not null,
  scheduled_for timestamptz not null,
  sent_at timestamptz,
  status reminder_status not null default 'scheduled',
  template_key text not null,
  last_error text,
  created_at timestamptz not null default now()
);
create index reminders_engagement_idx on reminders(engagement_id);
create index reminders_due_idx on reminders(status, scheduled_for);

create table templates (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid references firms(id) on delete cascade,
  -- firm_id null = built-in / shared template.
  name text not null,
  type engagement_type not null default 'custom',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index templates_firm_id_idx on templates(firm_id);

create table activity_log (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid not null references firms(id) on delete cascade,
  engagement_id uuid references engagements(id) on delete cascade,
  actor_type activity_actor not null,
  actor_id text,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index activity_log_engagement_idx
  on activity_log(engagement_id, created_at desc);
create index activity_log_firm_idx
  on activity_log(firm_id, created_at desc);

create table jobs (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  run_after timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text,
  status job_status not null default 'pending',
  created_at timestamptz not null default now()
);
create index jobs_due_idx on jobs(status, run_after);

------------------------------------------------------------------------------
-- HELPER FUNCTIONS
------------------------------------------------------------------------------

create or replace function public.current_firm_id() returns uuid
language sql stable security definer set search_path = public
as $$
  select firm_id from public.users where id = auth.uid()
$$;

create or replace function public.is_firm_member(p_firm_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.users
    where id = auth.uid() and firm_id = p_firm_id
  )
$$;
